### ISSUE TITLE
e5 Player ?

### ISSUE THREAD

**Issue by lavara123** [enimax-anime/enimax#13]
Do you have a solution for e5 and e5-v2 player? Does it work in the app?

streamrapid

**Comment by soitchu** [comment]
Zoro uses e6 (rapidstream) and Fmovies uses e4 (rabbitstream). I am not sure what website uses e5, to be honest.

**Comment by enimax-anime** [comment]
What do you exactly mean by e5 player? Do you want the decryption key for e5 JavaScript file?

**Comment by lavara123** [comment]
> What do you exactly mean by e5 player? Do you want the decryption key for e5 JavaScript file?

This Web site e5 Player and e5-v2 player
https://www.2embed.to/embed/tmdb/movie?id=595586

I think it would be nice if e5 is added, I don't know if it uses fmovies, maybe e5 is working in your code, you should try it

**Comment by lavara123** [comment]
and fmovies original site fmovies.to I think it would be more functional if it was added

**Comment by enimax-anime** [comment]
Hmm. I'll look into it, but I don't wanna add more sources. It just makes it harder to maintain things.

**Comment by lavara123** [comment]
> Hmm. I'll look into it, but I don't wanna add more sources. It just makes it harder to maintain things.

Good luck with your spirit. You might consider replacing fmovies.app with fmovies.to because its original site is fmovies.to 👍
