### ISSUE TITLE
Eval function 

### ISSUE THREAD

**Issue by lavara123** [enimax-anime/enimax#14]
Any chance of working without eval?

https://github.com/enimax-anime/enimax-chrome-extension/blob/de935b0671e7dd8d0c58c7c6a920b8dfe838b7a2/www/eval.html#L6

**Comment by enimax-anime** [comment]
No, actually. It's in a sandboxed iframe, so it shouldn't be an issue, I don't think. I do remember checking it when I implemented it; I'll get back to you when I have confirmed that. I know for sure it doesn't matter on the android app.

Anyway, when I switch to manifest v3, eval.html will be a sandboxed file, so it will actually not matter.

**Comment by lavara123** [comment]
@enimax-anime

Are functions in eval variable or fixed?

**Comment by enimax-anime** [comment]
They are variable. It is used to extract the decryption key for Zoro and Fmovies. I just realized the `chrome` variable is still accessible in the sandboxed iframe. It's a major security flaw and I'll work on fixing it ASAP. However, this does not affect the android app.

**Comment by enimax-anime** [comment]
The chrome extension has been fixed and it no longer evals the function. However, the firefox extension wasn't affected by it so I will push the change when I update it to v1.2.2.

**Comment by lavara123** [comment]
> The chrome extension has been fixed and it no longer evals the function. However, the firefox extension wasn't affected by it so I will push the change when I update it to v1.2.2.

👍👍

What is the duration of the generated keys?
