### ISSUE TITLE
Error while playing stream 

### ISSUE THREAD

**Issue by charlie239-CU** [enimax-anime/enimax#26]
![IMG-20230522-WA0013](https://github.com/enimax-anime/enimax/assets/60192161/9a85764d-e7f7-4c80-ad2e-a90960a1072d)

**Comment by enimax-anime** [comment]
What source were you using, and what show is that?

**Comment by enimax-anime** [comment]
That's really weird. Could you normally access these pages? Can you open the info open?

**Comment by enimax-anime** [comment]
Closing because there was no response.
