### ISSUE TITLE
Fmovies Malformed UTF-8 data

### ISSUE THREAD

**Issue by rahuloberai** [enimax-anime/enimax#33]
Getting Malformed UTF-8 data while parsing m3u8 file. 
Can you please have a look.

**Comment by enimax-anime** [comment]
Hi! It's a known issue. The keys are broken, that's why you're getting that message. I will try fixing that ASAP. I'd recommend that you join the discord server if you want the dev builds!

**Comment by enimax-anime** [comment]
Fixed.
