### ISSUE TITLE
few suggestions

### ISSUE THREAD

**Issue by sgrxrx** [enimax-anime/enimax#36]
Would it be possible for you to add animepahe and (cr scrapper) as a source(atleast animepahe)? They update their releases with bds so it would be nice to have that.
I think the feature to control your volume and brightness via player would be a good addition to the app. (im loving the app btw, the ui is pretty clean and the discover section is pretty good as well with just showing current and next season)

**Comment by enimax-anime** [comment]
I'll add those to my to-do list! Thank you!!

**Comment by enimax-anime** [comment]
Oh, i forgot to mention that the app does have Kickassanime, which scrape from Crunchyroll.

**Comment by sgrxrx** [comment]
ohh thank you.

**Comment by enimax-anime** [comment]
An update: animepahe has been added. You can download it from the [dev](https://github.com/enimax-anime/enimax-dev/releases/latest) branch

**Comment by sgrxrx** [comment]
awesome, just updated it and it works. Thank you.

**Comment by enimax-anime** [comment]
Added in the latest dev release. You can slide up/down on the left/right side of the screen to change the brightness/volume.
