### ISSUE TITLE
Search and download option bug

### ISSUE THREAD

**Issue by GoluLiliput** [enimax-anime/enimax#40]
The app search is bugged. No matter what u search in whatever category, it rolls back to anime category. Though the search results appear correctly.

**Comment by enimax-anime** [comment]
> The app search is bugged. No matter what u search in whatever category, it rolls back to anime category. Though the search results appear correctly.

What release channel are you on? Beta?

**Comment by enimax-anime** [comment]
> Also, when downloading episode, a dialogue appears asking me for selecting server. When I press 'Cancel', the dialogue box reappears.

Yes, because it needs you to select one of them. This should only appear the first time you download something from a specific source.

**Comment by GoluLiliput** [comment]
> > The app search is bugged. No matter what u search in whatever category, it rolls back to anime category. Though the search results appear correctly.
> 
> What release channel are you on? Beta?

Yes I am on dev builds

**Comment by enimax-anime** [comment]
Oh, I was able to replicate that search bug. I'm assuming you're on the latest dev build?

**Comment by GoluLiliput** [comment]
> > Also, when downloading episode, a dialogue appears asking me for selecting server. When I press 'Cancel', the dialogue box reappears.
> 
> Yes, because it needs you to select one of them. This should only appear the first time you download something from a specific source.

No I mean, when I press cancel, the dialogue box should cancel. But rather it forces me to choose one option. It's so persistent that even if I close the app and reopen it, the first thing it shows is that dialogue box. The only option I m left with is to either choose an option and app forcefully starts downloading or i have to clear the app data. Try downloading any anime from Zoro in the app, u can reproduce what I m trying to say.

**Comment by GoluLiliput** [comment]
> Oh, I was able to replicate that search bug. I'm assuming you're on the latest dev build?

Yes I am. I absolutely love this app. It's is unbelievably functional. Much much better than what is already available out there. There are few issues and bugs here and there but the app is simply lit🔥🔥🔥🔥

**Comment by enimax-anime** [comment]
I know, but it needs that to download them. You can select something to dismiss it. 

That said, I'll make it so it fallbacks on the first option if it's cancelled. But I think that'll create more issues than just selecting something.

**Comment by enimax-anime** [comment]
> > Oh, I was able to replicate that search bug. I'm assuming you're on the latest dev build?
> 
> Yes I am. I absolutely love this app. It's is unbelievably functional. Much much better than what is already available out there. There are few issues and bugs here and there but the app is simply lit🔥🔥🔥🔥

Thank you! The search bug should be fixed later today. I'll also look into modifying the download prompt :)

**Comment by GoluLiliput** [comment]
> I know, but it needs that to download them. You can select something to dismiss it. 
> 
> That said, I'll make it so it fallbacks on the first option if it's cancelled. But I think that'll create more issues than just selecting something.

I understand but that 'Cancel' button there doesn't all that sense anymore then. Anyways u can see what could be done about it.

**Comment by enimax-anime** [comment]
That's fair.

**Comment by GoluLiliput** [comment]
> > > Oh, I was able to replicate that search bug. I'm assuming you're on the latest dev build?
> > 
> > Yes I am. I absolutely love this app. It's is unbelievably functional. Much much better than what is already available out there. There are few issues and bugs here and there but the app is simply lit🔥🔥🔥🔥
> 
> Thank you! The search bug should be fixed later today. I'll also look into modifying the download prompt :)

Brother. If u wouldn't mind, I would be glad to help u create a discord server for this app. I really want people to appreciate this app as much as possible and i really want to contribute my fullest in the best possible way for development of this app.

**Comment by enimax-anime** [comment]
> > > > Oh, I was able to replicate that search bug. I'm assuming you're on the latest dev build?
> > > 
> > > 
> > > Yes I am. I absolutely love this app. It's is unbelievably functional. Much much better than what is already available out there. There are few issues and bugs here and there but the app is simply lit🔥🔥🔥🔥
> > 
> > 
> > Thank you! The search bug should be fixed later today. I'll also look into modifying the download prompt :)
> 
> Brother. If u wouldn't mind, I would be glad to help u create a discord server for this app. I really want people to appreciate this app as much as possible and i really want to contribute my fullest in the best possible way for development of this app.

There's already a discord server actually. The link was in the [readme](https://github.com/enimax-anime/enimax/#enimax) :p Maybe I need to make it more apparent? But yeah, here you go: https://discord.gg/cumVkBuU57

**Comment by GoluLiliput** [comment]
> > > > > Oh, I was able to replicate that search bug. I'm assuming you're on the latest dev build?
> > > > 
> > > > 
> > > > Yes I am. I absolutely love this app. It's is unbelievably functional. Much much better than what is already available out there. There are few issues and bugs here and there but the app is simply lit🔥🔥🔥🔥
> > > 
> > > 
> > > Thank you! The search bug should be fixed later today. I'll also look into modifying the download prompt :)
> > 
> > Brother. If u wouldn't mind, I would be glad to help u create a discord server for this app. I really want people to appreciate this app as much as possible and i really want to contribute my fullest in the best possible way for development of this app.
> 
> There's already a discord server actually. The link was in the [readme](https://github.com/enimax-anime/enimax/#enimax) :p Maybe I need to make it more apparent? But yeah, here you go: https://discord.gg/cumVkBuU57
> 

Yes I need to make it a bit more apparent😂
Anyways thank u!

**Comment by enimax-anime** [comment]
It should be fixed in the latest dev build.
