### ISSUE TITLE
Few bugs and few syggestions

### ISSUE THREAD

**Issue by GoluLiliput** [enimax-anime/enimax#42]
Firstly some bugs.. they are minor ones so i gues they can be fixed easily. I really have nothing much to complain about this app anyway. I use this app on daily basis so I was just noticing few of them so I thought about reporting them

1. Sometimes the episode description showed is showed entirely but still it shows the 'read more' button.![IMG_20230916_071758.jpg](https://github.com/enimax-anime/enimax/assets/60719832/bc426192-af15-40e3-9656-9b8568c66210)

2. When I open episode list from settings of the video player the UI shifts upwardswhile opening the list... as opposed to UI remaining perfectly normal when I open the episode list from the dedicated single button in the player. My suggestion would be to remove the episode list option from settings (cuz there is a direct button to do so in the player). 
![Screenshot_2023-09-17-09-03-50-253_com.enimax.hehe.jpg](https://github.com/enimax-anime/enimax/assets/60719832/3407cdb7-ddf9-4567-9c46-131b3a399ec8)

Also, if possible please make it so that when we open the episode list, the position of scroll in that list by default always shows the episode which is playing in the bottommost position, currently it shows episode 3 by default in the bottommost part, irrespective of any episode u are watching.

3. There is a few scaling issues here and there. For example here I can't click the 'more' button
![IMG_20230917_084714.jpg](https://github.com/enimax-anime/enimax/assets/60719832/6f81c7cb-1e5c-451b-9077-2beb35497e00)
I would suggest to make the UI of these elements more modern and fix the scaling issues. These UI are utilising old Android elements which lacks proper resolution and makes the app look old. Like there are few sliders in color adjustments within the app which are straight from Android 4.
![IMG_20230917_135008.jpg](https://github.com/enimax-anime/enimax/assets/60719832/175538d7-d020-4040-9acd-9917e666ccb8)

4. This is a small bug where there is minor scaling issue in the search screen where the title thumbnails overlap upon the sources button. In my phone it is touching the outer border of the source selection button but in another phone of mine it overlaps. So maybe increase padding between the source selection button and where the titles starts hiding off when scrolled.
![IMG_20230917_135437.jpg](https://github.com/enimax-anime/enimax/assets/60719832/76189fcf-69f5-4f54-a462-1b42dfb12dea)

Finally few suggestion:-

1. Instread of showing a dedicated slider button, u can maybe replace it with a small button accomodating a small space without usage of big-ass explanation of what it does. 
![IMG_20230916_071811.jpg](https://github.com/enimax-anime/enimax/assets/60719832/5c471782-cf9d-4be6-bd5d-78976efd37e1)
Instead with this type of button:
![IMG_20230917_140131.jpg](https://github.com/enimax-anime/enimax/assets/60719832/88a2fbc9-47ac-4c9f-8052-c5684e834f58)

2. Small suggestion but it would be great if u replace all the 'anilist/Anilist' text all around the app with 'AniList'. This would make the app feel more professional. I dunno but I would really like to see this happy, for some strange reason... so please?!?

3. It would be great if entire anime catalogue appears in anime section search by default instead of a blank screen, like wise for Movie&TV shows and Novel/Manga
![Screenshot_2023-09-17-14-08-18-137_com.enimax.hehe.jpg](https://github.com/enimax-anime/enimax/assets/60719832/dcdac856-e7ba-4c02-b28f-01ce91c527f7)

I guess that would be all for now. Thank u very very very very much creating such an awesome app for us all to enjoy. I m really grateful to u from the apex of my ❤️❤️❤️

**Comment by enimax-anime** [comment]
1. That's a deliberate choice. The way it's setup right now is that, to remove the `Read more` text, I'd need to check what the height of the container is, which is an expensive process. It can slow down the overall loading speed of the info page by half a second or so. I can probably look into a more optimal way of doing that.

2. It's already been setup that way. I think it scrolls to the 3rd episode because of the offset. I am assuming you were on the 1st episode? I can probably decrease the offset. But this issue should only happen if you're watching the first or the last few episodes.

4. That's the UI android webview provides. Nothing I can do to fix the issues it has. I can look into switching to a custom picker, but I am not sure if that's worth the hassle.

1. Noted

2. I am not sure where else I could move that toggle to such that it takes up less space.

3. Noted

4. I think displaying the shows that are on the website's home page would be better. Thought?

**Comment by GoluLiliput** [comment]
1. U can leave it the way it is. No problem. It was a minor thing and it doesn't matter.

2. The main thing I m trying to point out here is that the entire screen of the players moves vertically up a little when I open the episode list when going through 'settings->episodes' but this same issue doesn't occur if I directly press on the episode button placed in the player.
So my suggestion was to remove the episode list option from settings cuz: a. It will fix this screen shifting issue.     b. There is already a episode list button and uncluttering the UI is always a good thing.

3. Umm.. just if possible please switch to a custom picker cuz in small phones and older devices the entire UI of these old UI windows and elements scales really bad and even on my tablet it looks weird. So, no pressure, just if possible, make it a custom picker!

4. Appreciate that

5. U can move that button beside the episode range/season selection section when viewing episodes. Create a padding so that the episode range/season selection fades off beneath the button. 

6. Thank u very very much

7. That would be awesome ngl..


Finally thank u very much for hearing me out and pointing out what could be done and what couldn't be. I don't want to put any pressure on u cuz the app u made is proving so so very much useful to me, my friends and my family that I can't thank u enough.
Have a good day man! ❤️

**Comment by enimax-anime** [comment]
2. OHHH. I have known that issue for a bit. I should really fix that :p

3. I'll see what I can do :)

5. Hmm. I guess that would work. 

Ofc! Feel free to open more issues. Helps with polishing the app :) I appreciate it!!
That said, I'll close this issue for now and split this issues into multiple, which will make it easier to keep track of stuff.

**Comment by GoluLiliput** [comment]
> 2. OHHH. I have known that issue for a bit. I should really fix that :p
> 
> 3. I'll see what I can do :)
> 
> 5. Hmm. I guess that would work. 
> 
> Ofc! Feel free to open more issues. Helps with polishing the app :) I appreciate it!!
> That said, I'll close this issue for now and split this issues into multiple, which will make it easier to keep track of stuff.

Thank u very much!!
